

SELECT
CASE WHEN B.colid = 1 THEN 'SELECT ' + B.NAME
	ELSE ',' + B.NAME
END
,A.name
,B.name
,C.NAME
FROM SYSOBJECTS A
INNER JOIN SYSCOLUMNS B
ON A.ID = B.ID
INNER JOIN SYSTYPES C
ON B.XTYPE = C.xtype
WHERE A.XTYPE = 'U'
--AND B.NAME LIKE '%NOME%'
ORDER BY A.NAME,B.colid 

SELECT * FROM SYSOBJECTS WHERE XTYPE = 'U'
SELECT * FROM SYSOBJECTS WHERE XTYPE = 'P'
SELECT * FROM SYSOBJECTS WHERE XTYPE = 'V'
SELECT * FROM SYSOBJECTS WHERE XTYPE = 'FN'
SELECT * FROM SYSOBJECTS WHERE XTYPE = 'TF'

SP_HELPTEXT FN_LIMPA_VARCHAR

DECLARE @SQL VARCHAR(MAX) = ''

SELECT TOP 1
@SQL = 'SELECT * FROM ' + A.name + ' (NOLOCK) '
FROM SYSOBJECTS A
WHERE A.XTYPE = 'U'

EXEC (@SQL)


DECLARE @SQL VARCHAR(MAX) = ''

SET @SQL += 'SELECT 1'
SET @SQL += 'UNION ALL SELECT 2'
SET @SQL += 'UNION ALL SELECT 3'
SET @SQL += 'UNION ALL SELECT 4'
SET @SQL += 'UNION ALL SELECT 5'
SET @SQL += 'UNION ALL SELECT 6'
SET @SQL += ''

EXEC (@SQL)

CREATE PROC CONSULTA
	@ENTRADA INT
AS

DECLARE @SQL VARCHAR(MAX) = ''

IF @ENTRADA = 1
BEGIN
	SET @SQL += 'SELECT * FROM TB_PESSOAS'
END
ELSE
BEGIN
	SET @SQL += 'SELECT * FROM TB_GENERO'
END

EXEC (@SQL)

EXEC CONSULTA 2