
alter FUNCTION FN_LIMPA_VARCHAR (
	@TEXTO VARCHAR(300)
)
RETURNS VARCHAR(300)
AS
BEGIN
	
	DECLARE @RETORNO VARCHAR(300) = @TEXTO

	SET @RETORNO = REPLACE(@RETORNO,'í'	,'i')
	SET @RETORNO = REPLACE(@RETORNO,'á'	,'a')
	SET @RETORNO = REPLACE(@RETORNO,'-'	,' ')
	SET @RETORNO = REPLACE(@RETORNO,'ó'	,'o')
	SET @RETORNO = REPLACE(@RETORNO,'ä'	,'a')
	SET @RETORNO = REPLACE(@RETORNO,'.'	,'.')
	SET @RETORNO = REPLACE(@RETORNO,'ñ'	,'n')
	SET @RETORNO = REPLACE(@RETORNO,'é'	,'e')
	SET @RETORNO = REPLACE(@RETORNO,'å'	,'a')
	SET @RETORNO = REPLACE(@RETORNO,'Ø'	,'o')
	SET @RETORNO = REPLACE(@RETORNO,'ü'	,'u')
	SET @RETORNO = REPLACE(@RETORNO,'î'	,'i')
	SET @RETORNO = REPLACE(@RETORNO,'ö'	,'o')
	SET @RETORNO = REPLACE(@RETORNO,'''',' ') 
	SET @RETORNO = REPLACE(@RETORNO,'ß'	,'b')
	SET @RETORNO = REPLACE(@RETORNO,'ë'	,'e')
	SET @RETORNO = REPLACE(@RETORNO,'è'	,'e')
	SET @RETORNO = REPLACE(@RETORNO,'ê'	,'e')
	SET @RETORNO = REPLACE(@RETORNO,'ç'	,'c')
	SET @RETORNO = REPLACE(@RETORNO,'ð'	,'o')
	SET @RETORNO = REPLACE(@RETORNO,'ô'	,'o')
	SET @RETORNO = REPLACE(@RETORNO,'à'	,'a')
	SET @RETORNO = REPLACE(@RETORNO,'ï'	,'i')
	SET @RETORNO = REPLACE(@RETORNO,'ú'	,'u')
	SET @RETORNO = REPLACE(@RETORNO,'æ','ae')
	SET @RETORNO = REPLACE(@RETORNO,'û'	,'u')

	RETURN @RETORNO

END

GO

ALTER PROC SP_CONSULTA_PESSOA
	@CONSULTA VARCHAR(300)
AS

SELECT *
FROM TB_PESSOAS
where dbo.FN_LIMPA_VARCHAR(NOME_PESSOA) like '%' + dbo.FN_LIMPA_VARCHAR(@CONSULTA) + '%'
AND ATOR = 0 AND DIRETOR = 0


EXEC SP_CONSULTA_PESSOA 'rón'