--GERAR CONTADOR DE FILMES POR ANO
--GERAR CONTADOR DE FILMES POR IDIOMA
--GERAR CONTADOR DE FILMES POR PAIS

SELECT
	ANO/10*10
	,COUNT(1)
FROM VW_FILMES_DADOS
GROUP BY
	ANO/10*10
ORDER BY 1

SELECT
	IDIOMA
	,COUNT(1)
FROM VW_FILMES_DADOS
GROUP BY
	IDIOMA
ORDER BY 1

SELECT
	ISNULL(CONT,PAIS)
	--PAIS
	,COUNT(1)
FROM VW_FILMES_DADOS
LEFT JOIN (
			SELECT 'Brazil' P, 'AMERICA' CONT
UNION ALL	SELECT 'Canada' P, 'AMERICA' CONT
UNION ALL	SELECT 'USA' P, 'AMERICA' CONT
UNION ALL	SELECT 'Mexico' P, 'AMERICA' CONT
UNION ALL	SELECT 'Chile' P, 'AMERICA' CONT
UNION ALL	SELECT 'Peru' P, 'AMERICA' CONT
UNION ALL	SELECT 'Panama' P, 'AMERICA' CONT

UNION ALL	SELECT 'Japan' P, 'ASIA' CONT
UNION ALL	SELECT 'China' P, 'ASIA' CONT
UNION ALL	SELECT 'Hong Ko' P, 'ASIA' CONT

UNION ALL	SELECT 'Russia' P, 'EUROPA' CONT
UNION ALL	SELECT 'Sweden' P, 'EUROPA' CONT
UNION ALL	SELECT 'UK' P, 'EUROPA' CONT
) CONTINENTE
ON PAIS = P
GROUP BY
	ISNULL(CONT,PAIS)
	--PAIS
ORDER BY 1


SELECT
	PAIS
	,COUNT(1)
FROM VW_FILMES_DADOS
WHERE PAIS IN (
'Japan' ,
'China' ,
'Hong Ko'
)
GROUP BY
	PAIS
ORDER BY 1