--TB_PESSOAS

SELECT
	TB_PESSOAS.NOME_PESSOA
	,ISNULL(DIRETORES.QTD_FILMES_DIRIGIDOS, 0) QTD_FILMES_DIRIGIDOS
	,ISNULL(ATORES.QTD_FILMES_ATUADOS	  , 0) QTD_FILMES_ATUADOS	
FROM TB_PESSOAS
LEFT JOIN
--SELECT *
--FROM 
(SELECT
	DIRETOR
	,COUNT(1) QTD_FILMES_DIRIGIDOS
FROM VW_FILMES_DADOS
GROUP BY
	DIRETOR
) DIRETORES
ON TB_PESSOAS.NOME_PESSOA = DIRETORES.DIRETOR
--SELECT *
--FROM 
LEFT JOIN
(SELECT
	ATOR
	,COUNT(1) QTD_FILMES_ATUADOS
FROM (
          SELECT TITULO_FILME, ATOR_1 ATOR FROM VW_FILMES_DADOS
UNION ALL SELECT TITULO_FILME, ATOR_2 FROM VW_FILMES_DADOS
UNION ALL SELECT TITULO_FILME, ATOR_3 FROM VW_FILMES_DADOS
) X
--WHERE ATOR = 'Johnny Depp'
GROUP BY
	ATOR
) ATORES
ON TB_PESSOAS.NOME_PESSOA = ATORES.ATOR
