
UPDATE TABELA_1
SET CAMPOS_1 = DADO_1
FROM TABELA_1
INNER JOIN TABELA_2
ON TABELA_2.CAMPO_2 = TABELA_1.CAMPO_2


SELECT
 DIRETOR
,ATOR
,COUNT(1)
FROM TB_PESSOAS
GROUP BY
 DIRETOR
,ATOR



UPDATE TB_PESSOAS
SET DIRETOR = 1
FROM TB_PESSOAS X
INNER JOIN VW_FILMES_DADOS Y
ON X.NOME_PESSOA = Y.DIRETOR

UPDATE TB_PESSOAS
SET ATOR = 1
FROM TB_PESSOAS X
INNER JOIN VW_FILMES_DADOS Y
ON X.NOME_PESSOA = Y.ATOR_1
OR X.NOME_PESSOA = Y.ATOR_2
OR X.NOME_PESSOA = Y.ATOR_3

UPDATE TB_PESSOAS
SET DIRETOR = CASE WHEN X.NOME_PESSOA = Y.DIRETOR THEN 1 ELSE 0 END
,	ATOR	= CASE WHEN X.NOME_PESSOA = Y.ATOR_1 OR X.NOME_PESSOA = Y.ATOR_2 OR X.NOME_PESSOA = Y.ATOR_3 THEN 1 ELSE 0 END
FROM TB_PESSOAS X
INNER JOIN VW_FILMES_DADOS Y
ON X.NOME_PESSOA = Y.DIRETOR
OR X.NOME_PESSOA = Y.ATOR_1
OR X.NOME_PESSOA = Y.ATOR_2
OR X.NOME_PESSOA = Y.ATOR_3

