
CREATE VIEW VW_PESSOA_QTD_TRABALHOS
AS

SELECT
	NOME_PESSOA
	,SUM(DIRIGIDOS) QTD_FILMES_DIRIGIDOS
	,SUM(ATUADOS) QTD_FILMES_ATUADOS
FROM (
SELECT X.NOME_PESSOA, COUNT(1) DIRIGIDOS, 0 ATUADOS
FROM TB_PESSOAS X INNER JOIN VW_FILMES_DADOS Y ON X.NOME_PESSOA = Y.DIRETOR  GROUP BY X.NOME_PESSOA
UNION ALL
SELECT X.NOME_PESSOA, 0 DIRIGIDOS, COUNT(1) ATUADOS
FROM TB_PESSOAS X INNER JOIN VW_FILMES_DADOS Y ON X.NOME_PESSOA = Y.ATOR_1   GROUP BY X.NOME_PESSOA
UNION ALL
SELECT X.NOME_PESSOA, 0 DIRIGIDOS, COUNT(1) ATUADOS
FROM TB_PESSOAS X INNER JOIN VW_FILMES_DADOS Y ON X.NOME_PESSOA = Y.ATOR_2   GROUP BY X.NOME_PESSOA
UNION ALL
SELECT X.NOME_PESSOA, 0 DIRIGIDOS, COUNT(1) ATUADOS
FROM TB_PESSOAS X INNER JOIN VW_FILMES_DADOS Y ON X.NOME_PESSOA = Y.ATOR_3   GROUP BY X.NOME_PESSOA
) A
GROUP BY
	NOME_PESSOA

--SELECT
--	NOME
--	,SUM(QUANTIDADEA)
--	,SUM(QUANTIDADEB)
--FROM (
--		  SELECT 'MARCOS NAKA' NOME, 10 QUANTIDADEA, 1QUANTIDADEB
--UNION ALL SELECT 'MARCOS NAKA', 11, 2
--UNION ALL SELECT 'MARCOS NAKA', 12, 3
--UNION ALL SELECT 'MARCOS NAKA', 13, 4
--) A
--GROUP BY
--	NOME
